import Head from "next/head";

import styled from "styled-components";

import React from 'react'
import { Dropdown } from "@/components";

const Home = () => {
  return (
   <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
       <Conatiner>
        {/* <h1>Reusable Dropdown Component</h1> */}
        <Dropdown url="/api/options" />
        </Conatiner>
      </Section>
   </>
  )
}
  const Section = styled.section`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  min-height: 100vh;
  background: #C6FFDD;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #f7797d, #FBD786, #C6FFDD);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #f7797d, #FBD786, #C6FFDD); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

`;

const Conatiner = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  position: relative;
  padding: 4rem 0;


  &::before {
    content: "";
    background: var(--secondary-glow);
    border-radius: 50%;
    width: 480px;
    height: 360px;
    margin-left: -400px;
    position: absolute;
    left: 50%;
    filter: blur(45px);
  }

  &::after {
    content: "";
    background: linear-gradient(to right, #f64f59, #c471ed, #12c2e9);
    width: 240px;
    height: 180px;
    position: absolute;
    left: 50%;
    z-index: -1;
  }
`;


export default Home;