import Head from "next/head";
import { Inter } from "next/font/google";
import styled from "styled-components";

import React, { useState } from "react";
import {
  Dropdown,
  Modal
 } from "@/components";

const inter = Inter({ subsets: ["latin"] });

const HLD = [
 {
    id:1,
    title:"SnapShot of High Level Design",
    alt:"Brief Information about HLD ",
    imageUrl:"https://ik.imagekit.io/vndn6dm18/Screenshot%202024-08-31%20at%205.10.46%E2%80%AFPM.png?updatedAt=1725104456033",
    description:"Step1 :- Requirements"
  },
   {
    id:2,
    alt:"Brief Information about HLD",
    imageUrl:"https://ik.imagekit.io/vndn6dm18/Screenshot%202024-08-31%20at%205.13.38%E2%80%AFPM.png?updatedAt=1725104627679",
    description:"Step 2 ;- Architecture"
  },
     {
    id:3,
    alt:"Brief Information about HLD",
    imageUrl:"https://ik.imagekit.io/vndn6dm18/Screenshot%202024-08-31%20at%205.15.23%E2%80%AFPM.png?updatedAt=1725104730555",
    description:"Step 3 ;- Design and Implementation Details (Brief)"
  },
   {
    id:4,
    alt:"Brief Information about HLD",
    imageUrl:"https://ik.imagekit.io/vndn6dm18/Screenshot%202024-08-31%20at%205.15.23%E2%80%AFPM.png?updatedAt=1725104730555",
    description:"Step 4 ;- Operations and Optimization"
  },
];

const LLD = [
  {
    id:1,
    title:"SnapShot of code Implementation",
    alt:"Brief Information about LLD Implementation Part1",
    imageUrl:"https://ik.imagekit.io/vndn6dm18/code-1.png?updatedAt=1725102346972",
    description:"Encountered Interesting bugs and solved eventually"
  },
    {
    id:2,
    alt:"Brief Information about LLD Implementation part 2",
    imageUrl:"https://ik.imagekit.io/vndn6dm18/code-2.png?updatedAt=1725102347158",
    description:""
  }
];

const Audit = [
  {
    id:1,
    title:"Audit Reprt by Litehouse Tool",
    alt:"Brief Information LiteHouse Scores",
    imageUrl:"https://ik.imagekit.io/vndn6dm18/Audit.png?updatedAt=1725102329128",
    description:"Accessibility Score, SEO, Best Practices and Performance Scores will hepls to rank the Webpages which will have direct Imapct on SEO "
  },
]

const Home = () => {
	const [selectedOption1, setSelectedOption1] = useState([]);
	const [selectedOption2, setSelectedOption2] = useState([]);
  const [modalData, setModalData] = useState(HLD);
  const [openModel, setOpenModel] = useState(false);


	const clearSelection = (type) => type(null);

  const handleOpenModel = (type)=> {
    setModalData(type);
    setOpenModel(true);
  }

  const closeModal = ()=> {
    setOpenModel(false);
    setModalData([]);
  }

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Section>
				<Conatiner>
					<h1>Reusable Dropdown Component</h1>
					<DropdownsConatiner>
						<div>
							<h2>Dropdown With Internal Search Without API</h2>
							<Dropdown
                label="Workspace -1"
								url="/api/options"
								dropdownKey="dp-1"
								selectedOption={selectedOption1}
								setSelectedOption={setSelectedOption1}
							/>
							{selectedOption1?.length > 0 && (
								<SelectedOption>
								Selected:	<span> {selectedOption1?.[0]?.name}</span>
									<ClearButton
										onClick={() => clearSelection(setSelectedOption1)}
									>
										<i className="fa-solid fa-times-circle"></i> Clear
									</ClearButton>
								</SelectedOption>
							)}
						</div>
						<div>
							<h2>Dropdown With External Search With API</h2>
							<Dropdown
                label="Workspace -2"
								url="/api/options"
								searchExternal={true}
								dropdownKey="dp-2"
								selectedOption={selectedOption2}
								setSelectedOption={setSelectedOption2}
							/>
							{selectedOption2?.length > 0 && (
								<SelectedOption>
								Selected:	<span> {selectedOption2?.[0]?.name}</span>
									<ClearButton
										onClick={() => clearSelection(setSelectedOption2)}
									>
										<i className="fa-solid fa-times-circle"></i> Clear
									</ClearButton>
								</SelectedOption>
							)}
						</div>
					</DropdownsConatiner>
          <GridContainer>
       <h2>   Thought Proccess and Implementation Details</h2>
            <Grid>
          <Card
            className={inter.className}
            onClick={()=> handleOpenModel(HLD)}
          >
            <h2>
              HLD <span>-&gt;</span>
            </h2>
            <p>High Level Design of the Dropdown Search Component</p>
          </Card>

          <Card
            className={inter.className}
              onClick={()=> handleOpenModel(LLD)}
          >
            <h3>
              LLD <span>-&gt;</span>
            </h3>
            <p>Low Level Design Approach of the Dropdown Search Component</p>
          </Card>

          <Card
            className={inter.className}
            onClick={()=> handleOpenModel(Audit)}
          >
            <h4>
              Audit Reports <span>-&gt;</span>
            </h4>
            <p>
            This Audit Report Includes the Accessibility Score, SEO, Best Practices and Performance Scores
            </p>
          </Card>
        </Grid>
     <p>Built By Babajan for <span>AtomicWorks</span> Assignment</p>
          </GridContainer>
				</Conatiner>
			</Section>
      <Modal
       data={modalData}
       isOpen={openModel}
       closeModal={closeModal}
        />
		</>
	);
};
const Section = styled.section`
	display: flex;
	flex-direction: column;
	justify-content: space-between;
	align-items: center;
	min-height: 100vh;
	width: 100%;
`;

const Conatiner = styled.div`
	display: flex;
	flex-direction: column;
	justify-content: space-between;
	align-items: center;
	position: relative;
	padding: 4rem 2rem;
	gap: 2rem;
	/* width: 30rem; */
	text-align: center;

  h1{
    color: #0070f3;
  }

	@media (max-width: 768px) {
		width: 100%;
		font-size: 0.8rem;
	}
`;

const DropdownsConatiner = styled.div`
	display: flex;
	flex-direction: row;
	gap: 2rem;
  padding: 1rem;

	h2 {
		margin-bottom: 1rem;
	}

  @media (max-width: 768px) {
    flex-direction: column;
  }
`;

const GridContainer = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 10rem;
  gap: 1rem;
  flex-direction: column;

  @media (max-width: 768px) {
    gap: 1rem;
    margin-top: 4rem;
  }
`;

const Grid = styled.div`
	display: flex;
	flex-direction: row;
	gap: 2rem;
	margin-top: 2rem;
	z-index: 0;
	flex-wrap: wrap;
	justify-content: center;

	@media (max-width: 768px) {
		flex-direction: column;
	}
`;

const Card = styled.div`
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	width: 300px;
	height: 200px;
	padding: 1.5rem;
	border-radius: 12px;
	text-align: center;
	background: #fff;
	color: #333;
	text-decoration: none;
	box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
	transition: transform 0.3s, box-shadow 0.3s;
  cursor: pointer;

	&:hover {
		transform: rotate(3deg) scale(1.05);
		box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
	}

	h2,h3,h4 {
		margin: 0 0 1rem 0;
		font-size: 1.5rem;
		color: #0070f3;
	}

	p {
		margin: 0;
		font-size: 1rem;
		color: #666;
	}

	span {
		display: inline-block;
		transition: transform 0.2s;
	}

	&:hover span {
		transform: translateX(4px);
	}
`;

const SelectedOption = styled.div`
	margin-top: 1rem;
	display: flex;
	align-items: center;
	gap: 1rem;

  span {
    color: red;
  }
`;

const ClearButton = styled.button`
	border: none;
	background: transparent;
	color: #0070f3;
	cursor: pointer;
	font-size: 1rem;
	display: flex;
	align-items: center;

	&:hover {
		color: red;
	}

	i {
		margin-right: 0.5rem;
	}
`;

export default Home;
